budget_tracker/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("planner.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("admin/", admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
]

planner/urls.py
from django.urls import path

from planner.views import (
    index,
    register,
    BudgetCreateView,
    BudgetListView,
    BudgetUpdateView,
    BudgetDeleteView,
    CategoryListView,
    CategoryCreateView,
    CategoryDeleteView,
    CategoryUpdateView,
    TransactionCreateView,
    TransactionListView,
    TransactionUpdateView,
    TransactionDeleteView,
    TransferListView,
    TransferCreateView,
    TransferUpdateView,
    TransferDeleteView,
    ProfileDetailView,
    ProfileUpdateView,
)

urlpatterns = [
    path("", index, name="index"),
    path("register/", register, name="register"),
    path("profile/", ProfileDetailView.as_view(), name="profile"),
    path(
        "profile/update/",
        ProfileUpdateView.as_view(),
        name="profile-update"
    ),
    path("categories/", CategoryListView.as_view(), name="category-list"),
    path(
        "categories/create/",
        CategoryCreateView.as_view(),
        name="category-create"
    ),
    path(
        "categories/<int:pk>/update/",
        CategoryUpdateView.as_view(),
        name="category-update"
    ),
    path(
        "categories/<int:pk>/delete/",
        CategoryDeleteView.as_view(),
        name="category-delete"
    ),
    path("budgets/", BudgetListView.as_view(), name="budget-list"),
    path("budgets/create/", BudgetCreateView.as_view(), name="budget-create"),
    path(
        "budgets/<int:pk>/update/",
        BudgetUpdateView.as_view(),
        name="budget-update"
    ),
    path(
        "budgets/<int:pk>/delete/",
        BudgetDeleteView.as_view(),
        name="budget-delete"
    ),
    path(
        "transactions/",
        TransactionListView.as_view(),
        name="transaction-list"
    ),
    path(
        "transactions/create/",
        TransactionCreateView.as_view(),
        name="transaction-create"
    ),
    path(
        "transactions/<int:pk>/update/",
        TransactionUpdateView.as_view(),
        name="transaction-update"
    ),
    path(
        "transactions/<int:pk>/delete/",
        TransactionDeleteView.as_view(),
        name="transaction-delete"
    ),
    path("transfers/", TransferListView.as_view(), name="transfer-list"),
    path(
        "transfers/create/",
        TransferCreateView.as_view(),
        name="transfer-create"
    ),
    path(
        "transfers/<int:pk>/update/",
        TransferUpdateView.as_view(),
        name="transfer-update"
    ),
    path(
        "transfers/<int:pk>/delete/",
        TransferDeleteView.as_view(),
        name="transfer-delete"
    )
]

app_name = "planner"

templates/includes/confirm_delete_form.html
<form action="" method="post">
  {% csrf_token %}
  <div class="row g-0">
    <div class="col-sm-6 col-md-6">
      <input class="btn btn-secondary" type=button value="Cancel" onClick="history.go(-1);">
    </div>
    <div class="col-sm-6 col-md-6">
      <input type="submit" class="btn btn-danger" value="Yes, delete">
    </div>
  </div>
</form>
  

templates/includes/form.html
{% load crispy_forms_filters %}
<form action="" method="post">
  {% csrf_token %}
  {{ form|crispy }}
  <input class="btn btn-primary" type="submit" value="Submit">
</form>

templates/includes/pagination.html
{% load query_transform %}
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.previous_page_number %}" class="page-link">prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?{% query_transform request page=page_obj.next_page_number %}" class="page-link">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/search_form.html
{% load crispy_forms_filters %}
<form method="get" action="" class="form-inline">
    {{ search_form|crispy }}
    <input type="submit" value="🔍" class="btn btn-light">
  </form>

templates/includes/sidebar.html
<ul class="sidebar-nav list-group">
  {% if user.is_authenticated %}
    <li class="list-group-item">Hello, <a href="{% url 'planner:profile' %}">{{ user.username }}</a></li>
    <li class="list-group-item">
      <form method="post" action="{% url 'logout' %}">
        {% csrf_token %}
        <input class="btn btn-primary" type="submit" value="Logout">
      </form>
    </li>
  {% else %}
    <li class="list-group-item"><a href="{% url 'login' %}">Login</a></li>
    <li class="list-group-item"><a href="{% url 'planner:register' %}">Register</a></li>
  {% endif %}
  <br>
  <li class="list-group-item"><a href="{% url 'planner:index' %}">Home</a></li>
  <li class="list-group-item"><a href="{% url 'planner:category-list' %}">Categories</a></li>
  <li class="list-group-item"><a href="{% url 'planner:budget-list' %}">Budgets</a></li>
  <li class="list-group-item"><a href="{% url 'planner:transaction-list' %}">Transactions</a></li>
  <li class="list-group-item"><a href="{% url 'planner:transfer-list' %}">Transfers</a></li>
</ul>