budget_tracker/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("", include("planner.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("admin/", admin.site.urls),
    path("__debug__/", include("debug_toolbar.urls")),
]

planner/urls.py
from django.urls import path

from planner.views import (
    index,
    register,
    BudgetCreateView,
    BudgetListView,
    BudgetUpdateView,
    BudgetDeleteView,
    CategoryListView,
    CategoryCreateView,
    CategoryDeleteView,
    CategoryUpdateView,
    TransactionCreateView,
    TransactionListView,
    TransactionUpdateView,
    TransactionDeleteView,
    TransferListView,
    TransferCreateView,
    TransferUpdateView,
    TransferDeleteView,
    ProfileDetailView,
    ProfileUpdateView,
)

urlpatterns = [
    path("", index, name="index"),
    path("register/", register, name="register"),
    path("profile/", ProfileDetailView.as_view(), name="profile"),
    path(
        "profile/update/",
        ProfileUpdateView.as_view(),
        name="profile-update"
    ),
    path("categories/", CategoryListView.as_view(), name="category-list"),
    path(
        "categories/create/",
        CategoryCreateView.as_view(),
        name="category-create"
    ),
    path(
        "categories/<int:pk>/update/",
        CategoryUpdateView.as_view(),
        name="category-update"
    ),
    path(
        "categories/<int:pk>/delete/",
        CategoryDeleteView.as_view(),
        name="category-delete"
    ),
    path("budgets/", BudgetListView.as_view(), name="budget-list"),
    path("budgets/create/", BudgetCreateView.as_view(), name="budget-create"),
    path(
        "budgets/<int:pk>/update/",
        BudgetUpdateView.as_view(),
        name="budget-update"
    ),
    path(
        "budgets/<int:pk>/delete/",
        BudgetDeleteView.as_view(),
        name="budget-delete"
    ),
    path(
        "transactions/",
        TransactionListView.as_view(),
        name="transaction-list"
    ),
    path(
        "transactions/create/",
        TransactionCreateView.as_view(),
        name="transaction-create"
    ),
    path(
        "transactions/<int:pk>/update/",
        TransactionUpdateView.as_view(),
        name="transaction-update"
    ),
    path(
        "transactions/<int:pk>/delete/",
        TransactionDeleteView.as_view(),
        name="transaction-delete"
    ),
    path("transfers/", TransferListView.as_view(), name="transfer-list"),
    path(
        "transfers/create/",
        TransferCreateView.as_view(),
        name="transfer-create"
    ),
    path(
        "transfers/<int:pk>/update/",
        TransferUpdateView.as_view(),
        name="transfer-update"
    ),
    path(
        "transfers/<int:pk>/delete/",
        TransferDeleteView.as_view(),
        name="transfer-delete"
    )
]

app_name = "planner"

planner/models.py
from datetime import datetime

from django.contrib.auth import get_user_model
from django.db import models
from django.utils.translation import gettext_lazy as _
from djmoney.models.fields import MoneyField

User = get_user_model()


class Budget(models.Model):
    owner = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="budgets"
    )
    title = models.CharField(max_length=100)
    balance = MoneyField(
        max_digits=10, decimal_places=2, null=True, default_currency="USD"
    )

    def __str__(self):
        return f"{self.title} (balance: {self.balance})"


class Category(models.Model):
    title = models.CharField(max_length=100)
    owner = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="categories"
    )

    def __str__(self):
        return self.title


class Transaction(models.Model):
    class TransactionType(models.TextChoices):
        INCOME = "Income", _("Income")
        OUTCOME = "Outcome", _("Outcome")

    budget = models.ForeignKey(Budget, on_delete=models.CASCADE)
    category = models.ForeignKey(
        Category,
        on_delete=models.SET_NULL,
        null=True,
        related_name="transactions"
    )
    transaction_type = models.CharField(
        max_length=50, choices=TransactionType.choices
    )
    amount = MoneyField(
        max_digits=10, decimal_places=2, default_currency="USD"
    )
    date = models.DateTimeField(default=datetime.now)

    class Meta:
        ordering = ["-date", "category"]

    def save(self, *args, **kwargs):
        if self.pk:
            old_transaction = Transaction.objects.get(pk=self.pk)
            if old_transaction.transaction_type == self.TransactionType.INCOME:
                self.budget.balance -= old_transaction.amount
            elif (old_transaction.transaction_type
                  == self.TransactionType.OUTCOME):
                self.budget.balance += old_transaction.amount

        if self.transaction_type == self.TransactionType.INCOME:
            self.budget.balance += self.amount
        elif self.transaction_type == self.TransactionType.OUTCOME:
            self.budget.balance -= self.amount

        self.budget.save()
        super().save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        if self.transaction_type == self.TransactionType.INCOME:
            self.budget.balance -= self.amount
        elif self.transaction_type == self.TransactionType.OUTCOME:
            self.budget.balance += self.amount
        self.budget.save()
        super(Transaction, self).delete(*args, **kwargs)


class Transfer(models.Model):
    from_budget = models.ForeignKey(
        Budget, on_delete=models.CASCADE, related_name="outcomes"
    )
    to_budget = models.ForeignKey(
        Budget, on_delete=models.CASCADE, related_name="incomes"
    )
    amount = MoneyField(
        max_digits=10, decimal_places=2, default_currency="USD"
    )
    date = models.DateTimeField(default=datetime.now)

    class Meta:
        ordering = ["-date"]

    def save(self, *args, **kwargs):
        if self.pk:
            old_transfer = Transfer.objects.get(pk=self.pk)
            self.from_budget.balance += old_transfer.amount
            self.to_budget.balance -= old_transfer.amount

            old_transfer.from_budget.save()
            old_transfer.to_budget.save()

        self.from_budget.balance -= self.amount
        self.to_budget.balance += self.amount
        self.from_budget.save()
        self.to_budget.save()
        super().save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        if not self.pk:
            self.from_budget.balance += self.amount
            self.to_budget.balance -= self.amount
        self.from_budget.save()
        self.to_budget.save()
        super(Transfer, self).delete(*args, **kwargs)

planner/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError
from moneyed import Money

from planner.models import Budget, Transaction, Transfer, Category

User = get_user_model()


class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]


class TransactionForm(forms.ModelForm):
    class Meta:
        model = Transaction
        fields = ["transaction_type", "amount", "budget", "category", "date"]

    def __init__(self, *args, **kwargs):
        user = kwargs.pop("user")
        super().__init__(*args, **kwargs)
        self.fields["budget"].queryset = Budget.objects.filter(owner=user)
        self.fields["category"].queryset = Category.objects.filter(owner=user)

    def clean(self):
        cleaned_data = super().clean()
        budget = cleaned_data.get("budget")
        amount = cleaned_data.get("amount")
        total_digits = len(
            str(amount).replace('.', '').replace(',', '')
        )

        if budget and amount:
            if total_digits > 10:
                raise ValidationError(
                    "The total number of digits in the amount"
                    " must not exceed 8."
                )
            if budget.balance.currency != amount.currency:
                raise forms.ValidationError(
                    "The budget and transaction amount "
                    "must have the same currency."
                )

        return cleaned_data


class TransferForm(forms.ModelForm):
    class Meta:
        model = Transfer
        fields = ["from_budget", "to_budget", "amount", "date"]

    def __init__(self, *args, **kwargs):
        user = kwargs.pop("user")
        super().__init__(*args, **kwargs)
        self.fields["from_budget"].queryset = Budget.objects.filter(owner=user)
        self.fields["to_budget"].queryset = Budget.objects.filter(owner=user)

    def clean(self):
        cleaned_data = super().clean()
        from_budget = cleaned_data.get("from_budget")
        to_budget = cleaned_data.get("to_budget")
        amount = cleaned_data.get("amount")
        total_digits = len(
            str(amount).replace('.', '').replace(',', '')
        )

        if amount is None:
            raise ValidationError(
                "The total number of digits in the amount must not exceed 8."
            )

        if (
            from_budget
            and to_budget
            and from_budget.balance.currency != to_budget.balance.currency
        ):
            raise forms.ValidationError(
                "Both budgets must have the same currency for a transfer."
            )
        if from_budget == to_budget:
            raise ValidationError("From and To budgets cannot be the same.")
        if amount <= Money(0, amount.currency):
            raise ValidationError("Transfer amount must be greater than zero.")
        if from_budget.balance < amount:
            raise ValidationError("Insufficient funds in the source budget.")

        return cleaned_data


class DateSearchForm(forms.Form):
    start_date = forms.DateField(
        widget=forms.DateInput(attrs={"type": "date"}), required=False
    )
    end_date = forms.DateField(
        widget=forms.DateInput(attrs={"type": "date"}), required=False
    )

planner/views.py
from django.contrib import messages
from django.contrib.auth import login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import generic

from planner.forms import (
    RegisterForm,
    TransactionForm,
    TransferForm,
    DateSearchForm,
)
from planner.models import Category, Budget, Transaction, Transfer


class BaseListViewWithDateSearch(LoginRequiredMixin, generic.ListView):

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        form = DateSearchForm(self.request.GET)
        context["search_form"] = form
        return context

    def get_queryset(self):
        queryset = super().get_queryset()
        form = DateSearchForm(self.request.GET)
        if form.is_valid():
            start_date = form.cleaned_data.get("start_date")
            end_date = form.cleaned_data.get("end_date")
            if start_date:
                queryset = queryset.filter(date__gte=start_date)
            if end_date:
                queryset = queryset.filter(date__lte=end_date)
        return queryset


def index(request):
    return render(request, "planner/index.html")


def register(request) -> HttpResponse:
    if request.method == "GET":
        form = RegisterForm()
        return render(request, "registration/register.html", {"form": form})

    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save(commit=False)
            user.save()
            messages.success(request, "You have singed up successfully.")
            login(request, user)
            return redirect("planner:index")

        return render(
            request,
            "registration/register.html",
            {"form": form}
        )


class ProfileDetailView(LoginRequiredMixin, generic.DetailView):
    model = User
    context_object_name = "user"

    def get_object(self, queryset=None):
        return self.request.user


class ProfileUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = User
    fields = ["first_name", "last_name", "username", "email"]
    success_url = reverse_lazy("planner:profile")

    def get_object(self, queryset=None):
        return self.request.user


class CategoryListView(LoginRequiredMixin, generic.ListView):
    model = Category
    context_object_name = "category_list"
    template_name = "planner/category_list.html"
    queryset = Category.objects.select_related("owner")
    paginate_by = 10


class CategoryCreateView(LoginRequiredMixin, generic.CreateView):
    model = Category
    fields = ["title"]
    success_url = reverse_lazy("planner:category-list")

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class CategoryUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Category
    fields = ["title"]
    success_url = reverse_lazy("planner:category-list")


class CategoryDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Category
    success_url = reverse_lazy("planner:category-list")


class BudgetListView(LoginRequiredMixin, generic.ListView):
    model = Budget
    context_object_name = "budget_list"
    template_name = "planner/budget_list.html"
    queryset = Budget.objects.select_related("owner")
    paginate_by = 10


class BudgetCreateView(LoginRequiredMixin, generic.CreateView):
    model = Budget
    fields = ["title", "balance"]
    success_url = reverse_lazy("planner:budget-list")

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class BudgetUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Budget
    fields = ["title", "balance"]
    success_url = reverse_lazy("planner:budget-list")


class BudgetDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Budget
    success_url = reverse_lazy("planner:budget-list")


class TransactionListView(BaseListViewWithDateSearch):
    model = Transaction
    context_object_name = "transaction_list"
    template_name = "planner/transaction_list.html"
    queryset = Transaction.objects.select_related("budget__owner", "category")
    paginate_by = 10


class TransactionCreateView(LoginRequiredMixin, generic.CreateView):
    model = Transaction
    form_class = TransactionForm
    success_url = reverse_lazy("planner:transaction-list")

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.request.user
        return kwargs

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class TransactionUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Transaction
    form_class = TransactionForm
    success_url = reverse_lazy("planner:transaction-list")

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.request.user
        return kwargs


class TransactionDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Transaction
    success_url = reverse_lazy("planner:transaction-list")


class TransferListView(BaseListViewWithDateSearch):
    model = Transfer
    context_object_name = "transfer_list"
    template_name = "planner/transfer_list.html"
    queryset = Transfer.objects.select_related(
        "from_budget__owner",
        "to_budget__owner"
    )
    paginate_by = 10


class TransferCreateView(LoginRequiredMixin, generic.CreateView):
    model = Transfer
    form_class = TransferForm
    success_url = reverse_lazy("planner:transfer-list")

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.request.user
        return kwargs

    def form_valid(self, form):
        form.instance.owner = self.request.user
        return super().form_valid(form)


class TransferUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Transfer
    form_class = TransferForm
    success_url = reverse_lazy("planner:transfer-list")

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.request.user
        return kwargs


class TransferDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Transfer
    success_url = reverse_lazy("planner:transfer-list")

templates/planner/budget_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <div class="alert alert-danger" role="alert">
    <h1>Delete {{ budget.title }} budget</h1>
    Are you sure that you want to delete {{ budget.title }} budget?
  </div>
  {% include 'includes/confirm_delete_form.html' %}
{% endblock %}

templates/planner/budget_form.html
{% extends "base.html" %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} Budget</h1>
  {% include "includes/form.html" %}
{% endblock %}

templates/planner/budget_list.html
{% extends 'base.html' %}

{% block content %}
  <h1>Budget list</h1>
  <p>
    <a class="btn btn-success" href="{% url 'planner:budget-create' %}">Create a new budget</a>
  </p>

  {% if budget_list %}
    <table class="table">
      <tr>
        <th>Title</th>
        <th>Balance</th>
        <th>Currency</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>
      {% for budget in budget_list %}
        {% if budget.owner.id == user.id %}
          <tr>
            <td>{{ budget.title }}</td>
            <td>{{ budget.balance }}</td>
            <td>{{ budget.balance_currency }}</td>
            <td><a class="btn btn-primary" href="{% url 'planner:budget-update' budget.id %}">Update</a></td>
            <td><a class="btn btn-danger" href="{% url 'planner:budget-delete' budget.id %}">Delete</a></td>
          </tr>
        {% endif %}
      {% endfor %}
    </table>
  {% else %}
    <p>There's no budget to display</p>
  {% endif %}
{% endblock %}

templates/planner/category_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <div class="alert alert-danger" role="alert">
    <h1>Delete {{ category.title }} category</h1>
    Are you sure that you want to delete {{ category.title }} category?
  </div>
  {% include 'includes/confirm_delete_form.html' %}
{% endblock %}

templates/planner/category_form.html
{% extends "base.html" %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} Category</h1>
  {% include "includes/form.html" %}
{% endblock %}

templates/planner/category_list.html
{% extends 'base.html' %}

{% block content %}
  <h1>Category list</h1>
  <p>
    <a class="btn btn-success" href="{% url 'planner:category-create' %}">Create new category</a>
  </p>
  {% if category_list %}
    <table class="table">
      <tr>
        <th>Title</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>
      {% for category in category_list %}
        {% if category.owner.id == user.id %}
          <tr>
            <td>{{ category.title }}</td>
            <td><a class="btn btn-primary" href="{% url 'planner:category-update' category.id %}">Update</a></td>
            <td><a class="btn btn-danger" href="{% url 'planner:category-delete' category.id %}">Delete</a></td>
          </tr>
        {% endif %}
      {% endfor %}
    </table>
  {% else %}
    <p>There's no category to display</p>
  {% endif %}
{% endblock %}

templates/planner/index.html
{% extends "base.html" %}

{% block content %}
  <h1>Planner</h1>
  <h4>Hello, and welcome to Planner app</h4>
  <p>This app will help you to manage your budgets. You can keep your spending data from different bank accounts and
    your cash spending in one place.</p>
  <p>You can create Categories and Budgets and make Transfers and Transactions with them.</p>
  <p>If you forgot to make your transfer in moment of spending, don't worry date is editable here, just choose date and
    time you need.</p>
  <p>You can have a negative balance in your budget which will represent your credits</p>
  {% if not user.is_authenticated %}
    <p><strong>To use app, please, login or register</strong></p>
  {% endif %}
{% endblock %}

templates/planner/transaction_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <div class="alert alert-danger" role="alert">
    <h1>Delete transaction</h1>
    Are you sure that you want to delete this transaction
    <strong>{{ transaction.transaction_type }} {{ transaction.amount }} {{ transaction.date }}</strong>?
  </div>
  {% include 'includes/confirm_delete_form.html' %}
{% endblock %}

templates/planner/transaction_form.html
{% extends "base.html" %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} Transaction</h1>
  {% include "includes/form.html" %}
{% endblock %}

templates/planner/transaction_list.html
{% extends 'base.html' %}

{% block content %}
  <h1>Transaction list</h1>
  <p>
    <a class="btn btn-success" href="{% url 'planner:transaction-create' %}">Create new transaction</a>
    {% include "includes/search_form.html" %}
  </p>
  {% if transaction_list %}
    <table class="table">
      <tr>
        <th>Type</th>
        <th>Amount</th>
        <th>Currency</th>
        <th>Date</th>
        <th>Category</th>
        <th>Budget</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>
      {% for transaction in transaction_list %}
        {% if transaction.budget.owner.id == user.id %}
          <tr>
            <td>{{ transaction.transaction_type }}</td>
            <td>{{ transaction.amount }}</td>
            <td>{{ transaction.amount_currency }}</td>
            <td>{{ transaction.date }}</td>
            <td>{{ transaction.category.title }}</td>
            <td>{{ transaction.budget.title }}</td>
            <td><a class="btn btn-primary" href="{% url 'planner:transaction-update' transaction.id %}">Update</a></td>
            <td><a class="btn btn-danger" href="{% url 'planner:transaction-delete' transaction.id %}">Delete</a></td>
          </tr>
        {% endif %}
      {% endfor %}
    </table>
  {% else %}
    <p>There's no transaction to display</p>
  {% endif %}
{% endblock %}

templates/planner/transfer_confirm_delete.html
{% extends "base.html" %}

{% block content %}
  <div class="alert alert-danger" role="alert">
    <h1>Delete transfer</h1>
    Are you sure that you want to delete this transfer
    <strong>From {{ transfer.from_budget.title }}
      to {{ transfer.to_budget.title }} {{ transfer.amount }} {{ transfer.date }}</strong>?
  </div>
  {% include 'includes/confirm_delete_form.html' %}
{% endblock %}

templates/planner/transfer_form.html
{% extends "base.html" %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} Transfer</h1>
  {% include "includes/form.html" %}
{% endblock %}

templates/planner/transfer_list.html
{% extends 'base.html' %}

{% block content %}
  <h1>Transfer list</h1>
  <p>
    <a class="btn btn-success" href="{% url 'planner:transfer-create' %}">Create new transfer</a>
    {% include "includes/search_form.html" %}
  </p>
  {% if transfer_list %}
    <table class="table">
      <tr>
        <th>From</th>
        <th>To</th>
        <th>Amount</th>
        <th>Date</th>
        <th>Update</th>
        <th>Delete</th>
      </tr>
      {% for transfer in transfer_list %}
        {% if transfer.from_budget.owner.id == user.id and transfer.to_budget.owner.id == user.id %}
          <tr>
            <td>{{ transfer.from_budget.title }}</td>
            <td>{{ transfer.to_budget.title }}</td>
            <td>{{ transfer.amount }}</td>
            <td>{{ transfer.date }}</td>
            <td><a class="btn btn-primary" href="{% url 'planner:transfer-update' transfer.id %}">Update</a></td>
            <td><a class="btn btn-danger" href="{% url 'planner:transfer-delete' transfer.id %}">Delete</a></td>
          </tr>
        {% endif %}
      {% endfor %}
    </table>
  {% else %}
    <p>There's no transfer to display</p>
  {% endif %}
{% endblock %}